'use client';

import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';

const ModelViewer = dynamic(() => import('@/components/ModelViewer'), {
  ssr: false,
  loading: () => (
    <div className="loading-container" style={{ minHeight: '300px' }}>
      <div className="loading-spinner" />
    </div>
  ),
});

const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://localhost:8001';

interface GalleryModel {
  id: string;
  name: string;
  url: string;
  source: string;
  file_size_mb: number;
}

export default function GalleryPage() {
  const [models, setModels] = useState<GalleryModel[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedModel, setSelectedModel] = useState<GalleryModel | null>(null);

  useEffect(() => {
    fetchModels();
  }, []);

  const fetchModels = async () => {
    try {
      const res = await fetch(`${BACKEND_URL}/api/gallery`, { cache: 'no-store' });
      if (!res.ok) throw new Error('Failed to fetch gallery');
      const data = await res.json();
      setModels(data.models);
    } catch (err: any) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="main-content" style={{ paddingTop: '40px', paddingBottom: '60px' }}>
      <div style={{ marginBottom: '40px', textAlign: 'center' }}>
        <h1 className="search-title" style={{ fontSize: '36px', marginBottom: '8px' }}>
          3D Model Gallery
        </h1>
        <p className="search-subtitle" style={{ margin: '0 auto' }}>
          Explore the growing collection of 3D models retrieved and generated by the SANKALP AI System.
        </p>
      </div>

      {loading && (
        <div className="loading-container">
          <div className="loading-spinner" />
          <div className="loading-text">Loading Gallery...</div>
        </div>
      )}

      {error && (
        <div className="empty-state">
          <div className="empty-icon">⚠️</div>
          <div className="empty-title">Connection Error</div>
          <div className="empty-description">{error}</div>
        </div>
      )}

      {!loading && !error && models.length === 0 && (
        <div className="empty-state">
          <div className="empty-icon">🗄️</div>
          <div className="empty-title">Gallery Empty</div>
          <div className="empty-description">
            Go to the Search page and query a concept to start populating this gallery.
          </div>
        </div>
      )}

      {!loading && !error && models.length > 0 && (
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
          gap: '24px'
        }}>
          {models.map((model) => (
            <div 
              key={model.id} 
              className="stage-card" 
              style={{ cursor: 'pointer', display: 'flex', flexDirection: 'column' }}
              onClick={() => setSelectedModel(model)}
            >
              <div style={{ height: '240px', background: 'var(--color-bg-secondary)', borderRadius: '8px', overflow: 'hidden', marginBottom: '16px', border: '1px solid rgba(255,255,255,0.05)' }}>
                {/* Embedded Viewer, simplified without controls */}
                <ModelViewer modelUrl={model.url} autoRotate={true} />
              </div>
              <div>
                <h3 className="stage-name">{model.name}</h3>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '4px' }}>
                  <span className="stage-detail" style={{ color: 'var(--color-text-muted)' }}>{model.source}</span>
                  <span className="stage-detail" style={{ fontWeight: 600 }}>{model.file_size_mb} MB</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Fullscreen Overlay Viewer */}
      {selectedModel && (
        <div style={{
          position: 'fixed',
          top: 0, left: 0, right: 0, bottom: 0,
          backgroundColor: 'rgba(10, 10, 18, 0.95)',
          zIndex: 100,
          display: 'flex',
          flexDirection: 'column',
          backdropFilter: 'blur(20px)'
        }}>
          <div style={{ padding: '24px 32px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--color-border)' }}>
            <div>
              <h2 className="model-name" style={{ margin: 0, fontSize: '24px' }}>{selectedModel.name}</h2>
              <p style={{ color: 'var(--color-text-secondary)', fontSize: '14px', marginTop: '4px' }}>
                {selectedModel.source} • {selectedModel.file_size_mb} MB
              </p>
            </div>
            <button 
              className="search-btn" 
              style={{ position: 'static', transform: 'none' }}
              onClick={() => setSelectedModel(null)}
            >
              ✕
            </button>
          </div>
          <div style={{ flex: 1, position: 'relative' }}>
            <ModelViewer modelUrl={selectedModel.url} autoRotate={true} />
          </div>
        </div>
      )}
    </div>
  );
}
